language: node_js
node_js:
- '4.1'
script: bash ./deploy.sh
env:
  global:
  - "-GH_REF": github.com/jvoigtlaender/ll1
  - secure: 19+qLXnsSPjK/zX3jQXFbmgcoM+4h6uXW8ZVMyH/U4DqEZpuP25tsHMWukjY6hxUtJoyGIU45bbJt2FHjIzgZ246ptE2IViQdg8U6FSPifKKeaHG9E3VtE+AyRg+mgylNzmM5pMPgyselTiT9MRPmIhiPWxB90AOPSCfNk3U69yjLa/4o42xG6kwtZOnxC3ep3O2e4Y6s781f6KnA/0iPCUFEESuXl4TzKTdVF/DAcvJo5IafWHZUEeYLPYbT49ptYh+nBheC5Y9HHChhIIaIbKfoSdtMQRO9mRnJMT4/TqR5HK6n3mHXAnpQY5Tsx1VPejByn2odnQMzBEb50RFZCRJhJuwHCKU0PerKQxfR2uaRPTV+hKu6qibXwlEc1g0r/OMaaHNBBJcsBeI/32dw/O5Xx4Jevc3uxxFKu6eCmzGIyY3HsV/qM21T7urAVdKCKuk4mv4b9GU6lQ1Xdw4nH4M1Xt7S7idph/zf9pdC5/QlBI9FKB2TLKKLjAt1maMSE5kyHonSuvr1cItHFLQmsyAr6muDe2mRvk4zyFXLYlGG+zXqUnMekQRMNrOt9cediaPiqWAtjfXVnpu5YeUeRzuXPu9a0X8htUH7JXJf+XqDO36k971+H9ipRQHeaoJEMIBfg2Nj6x7TaKHa3UQa7Uz+3MVcTtXC8plKfAQIUE=
